package jlack;

enum TokenType {
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_CURLY, RIGHT_CURLY,
    PLUS, MINUS, STAR, SLASH,
    DOT, COMMA, SEMICOLON,

    BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    LESS, LESS_EQUAL,
    GREATER, GREATER_EQUAL,

    IDENTIFIER, STRING, NUMBER,

    WRITE, WRITELN, LET, TRUE, FALSE, NIL, IF, ELSE,
    NOT, OR, AND, XOR, NOR, NAND,
    FOR, WHILE, REPEAT, UNTIL, BREAK, CONTINUE,
    FUN, RETURN, CLASS, THIS, SUPER,

    EOF
}